-- highlights-github-light.lua
-- Custom highlight groups for GitHub Light theme

local highlights = {
	NormalLineNr = { bg = "#ffffff" },
	LineNr = { bg = "#ffffff", fg = "#656d76" },
	CursorLineNr = { bg = "#ffffff", fg = "#24292f", bold = true },
	SignColumn = { bg = "#ffffff" },
	GitSignsAdd = { bg = "#ffffff", fg = "#1a7f37" },
	GitSignsChange = { bg = "#ffffff", fg = "#0969da" },
	GitSignsDelete = { bg = "#ffffff", fg = "#d1242f" },
	DiagnosticSignError = { bg = "#ffffff", fg = "#d1242f" },
	DiagnosticSignWarn = { bg = "#ffffff", fg = "#fb8500" },
	DiagnosticSignInfo = { bg = "#ffffff", fg = "#0969da" },
	DiagnosticSignHint = { bg = "#ffffff", fg = "#1a7f37" },
	VertSplit = { fg = "#d0d7de", bg = "#ffffff" },
	WinSeparator = { fg = "#d0d7de", bg = "#ffffff" },
	BufferLineOffset = { bg = "#f6f8fa", fg = "#f6f8fa", bold = true },
	BufferLineOffsetSeparator = { bg = "#f6f8fa", fg = "#f6f8fa" },
	BufferLineFill = { bg = "#f6f8fa" },
	TerminalNormal = { bg = "#ffffff" },
	TerminalBorder = { fg = "#ffffff", bg = "#ffffff" },
	Terminal = { bg = "#ffffff" },
	WhichKey = { fg = "#24292f", bg = "#ffffff" },
	WhichKeyGroup = { fg = "#0969da", bg = "#ffffff" },
	WhichKeyDesc = { fg = "#0550ae", bg = "#ffffff" },
	WhichKeyValue = { fg = "#0550ae", bg = "#ffffff" },
	WhichKeySeparator = { fg = "#656d76", bg = "#ffffff" },
	WhichKeyFloat = { bg = "#ffffff" },
	WhichKeyBorder = { fg = "#656d76", bg = "#ffffff" },
	WhichKeyTitle = { fg = "#656d76", bg = "#ffffff" },
	WhichKeyNormal = { bg = "#ffffff" },
	CmpPmenu = { bg = "#ffffff", fg = "#24292f" },
	CmpSel = { bg = "#dbeafe", fg = "#24292f" },
	CmpBorder = { fg = "#d0d7de", bg = "#ffffff" },
	CmpDoc = { bg = "#ffffff", fg = "#24292f" },
	CmpDocBorder = { fg = "#d0d7de", bg = "#ffffff" },
	CmpItemKindText = { fg = "#24292f" },
	CmpItemKindMethod = { fg = "#8250df" },
	CmpItemKindFunction = { fg = "#8250df" },
	CmpItemKindConstructor = { fg = "#8250df" },
	CmpItemKindField = { fg = "#0969da" },
	CmpItemKindVariable = { fg = "#0969da" },
	CmpItemKindClass = { fg = "#1a7f37" },
	CmpItemKindInterface = { fg = "#116329" },
	CmpItemKindModule = { fg = "#1a7f37" },
	CmpItemKindProperty = { fg = "#0969da" },
	CmpItemKindUnit = { fg = "#116329" },
	CmpItemKindValue = { fg = "#a0111f" },
	CmpItemKindEnum = { fg = "#1a7f37" },
	CmpItemKindKeyword = { fg = "#cf222e" },
	CmpItemKindSnippet = { fg = "#bf8700" },
	CmpItemKindColor = { fg = "#a0111f" },
	CmpItemKindFile = { fg = "#24292f" },
	CmpItemKindReference = { fg = "#0969da" },
	CmpItemKindFolder = { fg = "#24292f" },
	CmpItemKindEnumMember = { fg = "#0550ae" },
	CmpItemKindConstant = { fg = "#0550ae" },
	CmpItemKindStruct = { fg = "#1a7f37" },
	CmpItemKindEvent = { fg = "#8250df" },
	CmpItemKindOperator = { fg = "#24292f" },
	CmpItemKindTypeParameter = { fg = "#1a7f37" },
	CmpItemKindCodeium = { fg = "#0550ae" },
	CmpItemKindTextSel = { bg = "#24292f", fg = "#ffffff", bold = true },
	CmpItemKindMethodSel = { bg = "#8250df", fg = "#ffffff", bold = true },
	CmpItemKindFunctionSel = { bg = "#8250df", fg = "#ffffff", bold = true },
	CmpItemKindConstructorSel = { bg = "#8250df", fg = "#ffffff", bold = true },
	CmpItemKindFieldSel = { bg = "#0969da", fg = "#ffffff", bold = true },
	CmpItemKindVariableSel = { bg = "#0969da", fg = "#ffffff", bold = true },
	CmpItemKindClassSel = { bg = "#1a7f37", fg = "#ffffff", bold = true },
	CmpItemKindInterfaceSel = { bg = "#116329", fg = "#ffffff", bold = true },
	CmpItemKindModuleSel = { bg = "#1a7f37", fg = "#ffffff", bold = true },
	CmpItemKindPropertySel = { bg = "#0969da", fg = "#ffffff", bold = true },
	CmpItemKindUnitSel = { bg = "#116329", fg = "#ffffff", bold = true },
	CmpItemKindValueSel = { bg = "#a0111f", fg = "#ffffff", bold = true },
	CmpItemKindEnumSel = { bg = "#1a7f37", fg = "#ffffff", bold = true },
	CmpItemKindKeywordSel = { bg = "#cf222e", fg = "#ffffff", bold = true },
	CmpItemKindSnippetSel = { bg = "#bf8700", fg = "#ffffff", bold = true },
	CmpItemKindColorSel = { bg = "#a0111f", fg = "#ffffff", bold = true },
	CmpItemKindFileSel = { bg = "#24292f", fg = "#ffffff", bold = true },
	CmpItemKindReferenceSel = { bg = "#0969da", fg = "#ffffff", bold = true },
	CmpItemKindFolderSel = { bg = "#24292f", fg = "#ffffff", bold = true },
	CmpItemKindEnumMemberSel = { bg = "#0550ae", fg = "#ffffff", bold = true },
	CmpItemKindConstantSel = { bg = "#0550ae", fg = "#ffffff", bold = true },
	CmpItemKindStructSel = { bg = "#1a7f37", fg = "#ffffff", bold = true },
	CmpItemKindEventSel = { bg = "#8250df", fg = "#ffffff", bold = true },
	CmpItemKindOperatorSel = { bg = "#24292f", fg = "#ffffff", bold = true },
	CmpItemKindTypeParameterSel = { bg = "#1a7f37", fg = "#ffffff", bold = true },
	CmpItemKindCodeiumSel = { bg = "#0550ae", fg = "#ffffff", bold = true },
	CmpScrollbar = { bg = "#f6f8fa" },
	CmpScrollbarThumb = { bg = "#d0d7de" },
	PmenuSbar = { bg = "#f6f8fa" },
	PmenuThumb = { bg = "#d0d7de" },
	HLIndent1 = { fg = "#eaeef2" },
	HLChunk1 = { fg = "#0969da" },
	InclineNormal = { bg = "#f6f8fa" },
	InclineNormalNC = { bg = "#f6f8fa" },
	MintyFloatBorder = { fg = "#d0d7de", bg = "#ffffff" },
	MintyNormal = { bg = "#ffffff" },
	NoiceCmdlinePopup = { bg = "#ffffff", fg = "#24292f" },
	NoiceCmdlinePopupBorder = { bg = "#ffffff", fg = "#d0d7de" },
	NoiceCmdlineIconCmdline = { bg = "#ffffff", fg = "#d0d7de" },
	NoiceCmdlineIcon = { bg = "#ffffff", fg = "#d0d7de" },
	NoiceCmdlinePopupTitle = { bg = "#ffffff", fg = "#0550ae" },
	NoicePopup = { bg = "#ffffff", fg = "#24292f" },
	NoicePopupBorder = { bg = "#ffffff", fg = "#d0d7de" },
	NoiceConfirm = { bg = "#ffffff", fg = "#24292f" },
	NoiceConfirmBorder = { bg = "#ffffff", fg = "#d0d7de" },
	NoiceMini = { bg = "#ffffff", fg = "#24292f" },
	NoiceFormatProgressDone = { bg = "#ffffff", fg = "#1a7f37" },
	NoiceFormatProgressTodo = { bg = "#ffffff", fg = "#656d76" },
	NoiceFormatTitle = { bg = "#ffffff", fg = "#0550ae" },
	NoiceFormatEvent = { bg = "#ffffff", fg = "#1a7f37" },
	NoiceFormatKind = { bg = "#ffffff", fg = "#8250df" },
	NoiceFormatDate = { bg = "#ffffff", fg = "#bf8700" },
	NoiceLspProgressTitle = { bg = "#ffffff", fg = "#0550ae" },
	NoiceLspProgressClient = { bg = "#ffffff", fg = "#1a7f37" },
	NoiceLspProgressSpinner = { bg = "#ffffff", fg = "#8250df" },
	NoiceCmdlinePrompt = { bg = "#ffffff", fg = "#0550ae" },
	MsgArea = { bg = "#ffffff", fg = "#24292f" },
	MsgSeparator = { bg = "#ffffff", fg = "#d0d7de" },
	NormalFloat = { bg = "#ffffff", fg = "#24292f" },
	FloatBorder = { bg = "#ffffff", fg = "#d0d7de" },
	Pmenu = { bg = "#f6f8fa", fg = "#24292f" },
	PmenuSel = { bg = "#dbeafe", fg = "#24292f" },
	PmenuBorder = { bg = "#f6f8fa", fg = "#d0d7de" },
	NeoTreeNormal = { bg = "#f6f8fa" },
	NeoTreeNormalNC = { bg = "#f6f8fa" },
	NeoTreeEndOfBuffer = { bg = "#f6f8fa", fg = "#f6f8fa" },
	NeoTreeWinSeparator = { fg = "#F6F8FA", bg = "#f6f8fa" },
	NeoTreeGitAdded = { bg = "#f6f8fa", fg = "#1a7f37" },
	NeoTreeGitConflict = { bg = "#f6f8fa", fg = "#d1242f" },
	NeoTreeGitDeleted = { bg = "#f6f8fa", fg = "#d1242f" },
	NeoTreeGitIgnored = { bg = "#f6f8fa", fg = "#8c959f" },
	NeoTreeGitModified = { bg = "#f6f8fa", fg = "#0969da" },
	NeoTreeGitUnstaged = { bg = "#f6f8fa", fg = "#fb8500" },
	NeoTreeGitUntracked = { bg = "#f6f8fa", fg = "#1a7f37" },
	NeoTreeGitStaged = { bg = "#f6f8fa", fg = "#1a7f37" },
	EndOfBuffer = { fg = "#ffffff" },
	ColorColumn = { bg = "#f6f8fa" },
	VirtColumn = { fg = "#f6f8fa" },
}

return highlights
