-- highlights-kanagawa-lotus.lua
-- Custom highlight groups for Kanagawa Lotus theme (Light)

local highlights = {
	LineNr = { bg = "#F2ECBC" },
	CursorLineNr = { bg = "#F2ECBC", bold = true },
	SignColumn = { bg = "#F2ECBC" },
	GitSignsAdd = { bg = "#F2ECBC", fg = "#228B22" },
	GitSignsChange = { bg = "#F2ECBC", fg = "#B8860B" },
	GitSignsDelete = { bg = "#F2ECBC", fg = "#DC143C" },
	DiagnosticSignError = { bg = "#F2ECBC", fg = "#DC143C" },
	DiagnosticSignWarn = { bg = "#F2ECBC", fg = "#B8860B" },
	DiagnosticSignInfo = { bg = "#F2ECBC", fg = "#4D699B" },
	DiagnosticSignHint = { bg = "#F2ECBC", fg = "#8B008B" },
	VertSplit = { bg = "#C1BC96", fg = "#C1BC96" },
	WinSeparator = { bg = "#C1BC96", fg = "#C1BC96" },
	BufferLineOffset = { bg = "#C1BC96", fg = "#C1BC96", bold = true },
	BufferLineOffsetSeparator = { bg = "#C1BC96", fg = "#C1BC96" },
	WhichKey = { fg = "#4D699B", bg = "#F2ECBC" },
	WhichKeyGroup = { fg = "#8A8A8A", bg = "#F2ECBC" },
	WhichKeyDesc = { fg = "#2A2A37", bg = "#F2ECBC" },
	WhichKeyValue = { fg = "#2A2A37", bg = "#F2ECBC" },
	WhichKeySeparator = { fg = "#8A8A8A", bg = "#F2ECBC" },
	WhichKeyFloat = { bg = "#F2ECBC" },
	WhichKeyBorder = { fg = "#8A8A8A", bg = "#F2ECBC" },
	WhichKeyTitle = { fg = "#8A8A8A", bg = "#F2ECBC" },
	WhichKeyNormal = { bg = "#F2ECBC" },
	NoicePopup = { bg = "#F2ECBC", fg = "#2A2A37" },
	NoicePopupBorder = { bg = "#F2ECBC", fg = "#8A8A8A" },
	NoiceCmdlinePrompt = { bg = "#F2ECBC", fg = "#4D699B" },
	ThemeryTitle = { bg = "#F2ECBC", fg = "#2A2A37" },
	ThemeryBorder = { bg = "#F2ECBC", fg = "#2A2A37" },
	ThemeryNormal = { bg = "#F2ECBC", fg = "#2A2A37" },
	ThemeryFloat = { bg = "#F2ECBC" },
	NoiceCmdlinePopup = { bg = "#F2ECBC", fg = "#2A2A37" },
	NoiceCmdlinePopupBorder = { bg = "#F2ECBC", fg = "#8A8A8A" },
	NoiceCmdlineIconCmdline = { bg = "#F2ECBC", fg = "#8A8A8A" },
	NoiceCmdlineIcon = { bg = "#F2ECBC", fg = "#8A8A8A" },
	NoiceCmdlinePopupTitle = { bg = "#F2ECBC", fg = "#4D699B" },
	NoiceConfirm = { bg = "#F2ECBC", fg = "#2A2A37" },
	NoiceConfirmBorder = { bg = "#F2ECBC", fg = "#8A8A8A" },
	NoiceMini = { bg = "#F2ECBC", fg = "#2A2A37" },
	NoiceFormatProgressDone = { bg = "#F2ECBC", fg = "#4D699B" },
	NoiceFormatProgressTodo = { bg = "#F2ECBC", fg = "#8A8A8A" },
	NoiceFormatTitle = { bg = "#F2ECBC", fg = "#4D699B" },
	NoiceFormatEvent = { bg = "#F2ECBC", fg = "#2A2A37" },
	NoiceFormatKind = { bg = "#F2ECBC", fg = "#4D699B" },
	NoiceFormatDate = { bg = "#F2ECBC", fg = "#8A8A8A" },
	NoiceLspProgressTitle = { bg = "#F2ECBC", fg = "#4D699B" },
	NoiceLspProgressClient = { bg = "#F2ECBC", fg = "#2A2A37" },
	NoiceLspProgressSpinner = { bg = "#F2ECBC", fg = "#4D699B" },
	MsgArea = { bg = "#F2ECBC", fg = "#2A2A37" },
	MsgSeparator = { bg = "#F2ECBC", fg = "#8A8A8A" },
	NormalFloat = { bg = "#F2ECBC", fg = "#2A2A37" },
	FloatBorder = { bg = "#F2ECBC", fg = "#8A8A8A" },
	Pmenu = { bg = "#F2ECBC", fg = "#2A2A37" },
	PmenuSel = { bg = "#C1BC96", fg = "#2A2A37" },
	PmenuBorder = { bg = "#F2ECBC", fg = "#8A8A8A" },
	MintyFloatBorder = { fg = "#8A8A8A", bg = "#F2ECBC" },
	MintyNormal = { bg = "#F2ECBC" },
	CmpPmenu = { bg = "#F2ECBC", fg = "#2A2A37" },
	CmpSel = { bg = "#C1BC96", fg = "#2A2A37" },
	CmpBorder = { fg = "#8A8A8A", bg = "#F2ECBC" },
	CmpDoc = { bg = "#F2ECBC", fg = "#2A2A37" },
	CmpDocBorder = { fg = "#8A8A8A", bg = "#F2ECBC" },
	CmpItemKindText = { fg = "#2A2A37" },
	CmpItemKindMethod = { fg = "#4D699B" },
	CmpItemKindFunction = { fg = "#4D699B" },
	CmpItemKindConstructor = { fg = "#4D699B" },
	CmpItemKindField = { fg = "#8A8A8A" },
	CmpItemKindVariable = { fg = "#2A2A37" },
	CmpItemKindClass = { fg = "#6B8E23" },
	CmpItemKindInterface = { fg = "#6B8E23" },
	CmpItemKindModule = { fg = "#6B8E23" },
	CmpItemKindProperty = { fg = "#8A8A8A" },
	CmpItemKindUnit = { fg = "#B8860B" },
	CmpItemKindValue = { fg = "#B8860B" },
	CmpItemKindEnum = { fg = "#6B8E23" },
	CmpItemKindKeyword = { fg = "#8B008B" },
	CmpItemKindSnippet = { fg = "#228B22" },
	CmpItemKindColor = { fg = "#DC143C" },
	CmpItemKindFile = { fg = "#4D699B" },
	CmpItemKindReference = { fg = "#6B8E23" },
	CmpItemKindFolder = { fg = "#4D699B" },
	CmpItemKindEnumMember = { fg = "#B8860B" },
	CmpItemKindConstant = { fg = "#B8860B" },
	CmpItemKindStruct = { fg = "#6B8E23" },
	CmpItemKindEvent = { fg = "#6B8E23" },
	CmpItemKindOperator = { fg = "#8B008B" },
	CmpItemKindTypeParameter = { fg = "#6B8E23" },
	CmpItemKindCodeium = { fg = "#4D699B" },
	CmpItemKindTextSel = { bg = "#2A2A37", fg = "#F2ECBC", bold = true },
	CmpItemKindMethodSel = { bg = "#4D699B", fg = "#F2ECBC", bold = true },
	CmpItemKindFunctionSel = { bg = "#4D699B", fg = "#F2ECBC", bold = true },
	CmpItemKindConstructorSel = { bg = "#4D699B", fg = "#F2ECBC", bold = true },
	CmpItemKindFieldSel = { bg = "#8A8A8A", fg = "#F2ECBC", bold = true },
	CmpItemKindVariableSel = { bg = "#2A2A37", fg = "#F2ECBC", bold = true },
	CmpItemKindClassSel = { bg = "#6B8E23", fg = "#F2ECBC", bold = true },
	CmpItemKindInterfaceSel = { bg = "#6B8E23", fg = "#F2ECBC", bold = true },
	CmpItemKindModuleSel = { bg = "#6B8E23", fg = "#F2ECBC", bold = true },
	CmpItemKindPropertySel = { bg = "#8A8A8A", fg = "#F2ECBC", bold = true },
	CmpItemKindUnitSel = { bg = "#B8860B", fg = "#F2ECBC", bold = true },
	CmpItemKindValueSel = { bg = "#B8860B", fg = "#F2ECBC", bold = true },
	CmpItemKindEnumSel = { bg = "#6B8E23", fg = "#F2ECBC", bold = true },
	CmpItemKindKeywordSel = { bg = "#8B008B", fg = "#F2ECBC", bold = true },
	CmpItemKindSnippetSel = { bg = "#228B22", fg = "#F2ECBC", bold = true },
	CmpItemKindColorSel = { bg = "#DC143C", fg = "#F2ECBC", bold = true },
	CmpItemKindFileSel = { bg = "#4D699B", fg = "#F2ECBC", bold = true },
	CmpItemKindReferenceSel = { bg = "#6B8E23", fg = "#F2ECBC", bold = true },
	CmpItemKindFolderSel = { bg = "#4D699B", fg = "#F2ECBC", bold = true },
	CmpItemKindEnumMemberSel = { bg = "#B8860B", fg = "#F2ECBC", bold = true },
	CmpItemKindConstantSel = { bg = "#B8860B", fg = "#F2ECBC", bold = true },
	CmpItemKindStructSel = { bg = "#6B8E23", fg = "#F2ECBC", bold = true },
	CmpItemKindEventSel = { bg = "#6B8E23", fg = "#F2ECBC", bold = true },
	CmpItemKindOperatorSel = { bg = "#8B008B", fg = "#F2ECBC", bold = true },
	CmpItemKindTypeParameterSel = { bg = "#6B8E23", fg = "#F2ECBC", bold = true },
	CmpItemKindCodeiumSel = { bg = "#4D699B", fg = "#F2ECBC", bold = true },
	CmpScrollbar = { bg = "#C1BC96" },
	CmpScrollbarThumb = { bg = "#4D699B" },
	HLIndent1 = { fg = "#8A8A8A" },
	HLIndent2 = { fg = "#8A8A8A" },
	HLIndent3 = { fg = "#8A8A8A" },
	HLIndent4 = { fg = "#8A8A8A" },
	HLIndent5 = { fg = "#8A8A8A" },
	HLChunk1 = { fg = "#2A2A37" },
	HLChunk2 = { fg = "#2A2A37" },
	HLChunk3 = { fg = "#2A2A37" },
	HLChunk4 = { fg = "#2A2A37" },
	HLChunk5 = { fg = "#2A2A37" },
	InclineNormal = { bg = "#C1BC96" },
	InclineNormalNC = { bg = "#C1BC96" },
	NeoTreeNormal = { bg = "#C1BC96" },
	NeoTreeNormalNC = { bg = "#C1BC96" },
	NeoTreeEndOfBuffer = { bg = "#C1BC96", fg = "#C1BC96" },
	ColorColumn = { bg = "#C1BC96" },
	VirtColumn = { fg = "#C1BC96" },
}

return highlights
