-- highlights-catppuccin-mocha.lua
-- Custom highlight groups for Catppuccin Mocha theme (Dark)

local highlights = {
	NormalLineNr = { bg = "#1e1e2e" },
	LineNr = { bg = "#1e1e2e", fg = "#45475a" },
	CursorLineNr = { bg = "#1e1e2e", fg = "#fab387", bold = true },
	SignColumn = { bg = "#1e1e2e" },
	GitSignsAdd = { bg = "#1e1e2e", fg = "#a6e3a1" },
	GitSignsChange = { bg = "#1e1e2e", fg = "#f9e2af" },
	GitSignsDelete = { bg = "#1e1e2e", fg = "#f38ba8" },
	DiagnosticSignError = { bg = "#1e1e2e", fg = "#f38ba8" },
	DiagnosticSignWarn = { bg = "#1e1e2e", fg = "#f9e2af" },
	DiagnosticSignInfo = { bg = "#1e1e2e", fg = "#89b4fa" },
	DiagnosticSignHint = { bg = "#1e1e2e", fg = "#cba6f7" },
	VertSplit = { fg = "#181825", bg = "#181825" },
	WinSeparator = { fg = "#181825", bg = "#181825" },
	BufferLineOffset = { bg = "#181825", fg = "#181825", bold = true },
	BufferLineOffsetSeparator = { bg = "#181825", fg = "#181825" },
	TerminalNormal = { bg = "#1e1e2e" },
	TerminalBorder = { fg = "#1e1e2e", bg = "#1e1e2e" },
	Terminal = { bg = "#1e1e2e" },
	WhichKey = { fg = "#cdd6f4", bg = "#1e1e2e" },
	WhichKeyGroup = { fg = "#585b70", bg = "#1e1e2e" },
	WhichKeyDesc = { fg = "#89b4fa", bg = "#1e1e2e" },
	WhichKeyValue = { fg = "#89b4fa", bg = "#1e1e2e" },
	WhichKeySeparator = { fg = "#585b70", bg = "#1e1e2e" },
	WhichKeyFloat = { bg = "#1e1e2e" },
	WhichKeyBorder = { fg = "#585b70", bg = "#1e1e2e" },
	WhichKeyTitle = { fg = "#585b70", bg = "#1e1e2e" },
	WhichKeyNormal = { bg = "#1e1e2e" },
	CmpPmenu = { bg = "#1e1e2e", fg = "#cdd6f4" },
	CmpSel = { bg = "#313244", fg = "#cdd6f4" },
	CmpBorder = { fg = "#585b70", bg = "#1e1e2e" },
	CmpDoc = { bg = "#1e1e2e", fg = "#cdd6f4" },
	CmpDocBorder = { fg = "#585b70", bg = "#1e1e2e" },
	CmpItemKindText = { fg = "#cdd6f4" },
	CmpItemKindMethod = { fg = "#89b4fa" },
	CmpItemKindFunction = { fg = "#89b4fa" },
	CmpItemKindConstructor = { fg = "#89b4fa" },
	CmpItemKindField = { fg = "#89dceb" },
	CmpItemKindVariable = { fg = "#cdd6f4" },
	CmpItemKindClass = { fg = "#f9e2af" },
	CmpItemKindInterface = { fg = "#f9e2af" },
	CmpItemKindModule = { fg = "#f9e2af" },
	CmpItemKindProperty = { fg = "#89dceb" },
	CmpItemKindUnit = { fg = "#fab387" },
	CmpItemKindValue = { fg = "#fab387" },
	CmpItemKindEnum = { fg = "#f9e2af" },
	CmpItemKindKeyword = { fg = "#cba6f7" },
	CmpItemKindSnippet = { fg = "#a6e3a1" },
	CmpItemKindColor = { fg = "#f38ba8" },
	CmpItemKindFile = { fg = "#89b4fa" },
	CmpItemKindReference = { fg = "#f9e2af" },
	CmpItemKindFolder = { fg = "#89b4fa" },
	CmpItemKindEnumMember = { fg = "#fab387" },
	CmpItemKindConstant = { fg = "#fab387" },
	CmpItemKindStruct = { fg = "#f9e2af" },
	CmpItemKindEvent = { fg = "#f9e2af" },
	CmpItemKindOperator = { fg = "#cba6f7" },
	CmpItemKindTypeParameter = { fg = "#f9e2af" },
	CmpItemKindCodeium = { fg = "#89b4fa" },
	CmpItemKindTextSel = { bg = "#cdd6f4", fg = "#1e1e2e", bold = true },
	CmpItemKindMethodSel = { bg = "#89b4fa", fg = "#1e1e2e", bold = true },
	CmpItemKindFunctionSel = { bg = "#89b4fa", fg = "#1e1e2e", bold = true },
	CmpItemKindConstructorSel = { bg = "#89b4fa", fg = "#1e1e2e", bold = true },
	CmpItemKindFieldSel = { bg = "#89dceb", fg = "#1e1e2e", bold = true },
	CmpItemKindVariableSel = { bg = "#cdd6f4", fg = "#1e1e2e", bold = true },
	CmpItemKindClassSel = { bg = "#f9e2af", fg = "#1e1e2e", bold = true },
	CmpItemKindInterfaceSel = { bg = "#f9e2af", fg = "#1e1e2e", bold = true },
	CmpItemKindModuleSel = { bg = "#f9e2af", fg = "#1e1e2e", bold = true },
	CmpItemKindPropertySel = { bg = "#89dceb", fg = "#1e1e2e", bold = true },
	CmpItemKindUnitSel = { bg = "#fab387", fg = "#1e1e2e", bold = true },
	CmpItemKindValueSel = { bg = "#fab387", fg = "#1e1e2e", bold = true },
	CmpItemKindEnumSel = { bg = "#f9e2af", fg = "#1e1e2e", bold = true },
	CmpItemKindKeywordSel = { bg = "#cba6f7", fg = "#1e1e2e", bold = true },
	CmpItemKindSnippetSel = { bg = "#a6e3a1", fg = "#1e1e2e", bold = true },
	CmpItemKindColorSel = { bg = "#f38ba8", fg = "#1e1e2e", bold = true },
	CmpItemKindFileSel = { bg = "#89b4fa", fg = "#1e1e2e", bold = true },
	CmpItemKindReferenceSel = { bg = "#f9e2af", fg = "#1e1e2e", bold = true },
	CmpItemKindFolderSel = { bg = "#89b4fa", fg = "#1e1e2e", bold = true },
	CmpItemKindEnumMemberSel = { bg = "#fab387", fg = "#1e1e2e", bold = true },
	CmpItemKindConstantSel = { bg = "#fab387", fg = "#1e1e2e", bold = true },
	CmpItemKindStructSel = { bg = "#f9e2af", fg = "#1e1e2e", bold = true },
	CmpItemKindEventSel = { bg = "#f9e2af", fg = "#1e1e2e", bold = true },
	CmpItemKindOperatorSel = { bg = "#cba6f7", fg = "#1e1e2e", bold = true },
	CmpItemKindTypeParameterSel = { bg = "#f9e2af", fg = "#1e1e2e", bold = true },
	CmpItemKindCodeiumSel = { bg = "#89b4fa", fg = "#1e1e2e", bold = true },
	CmpScrollbar = { bg = "#181825" },
	CmpScrollbarThumb = { bg = "#89b4fa" },
	PmenuSbar = { bg = "#181825" },
	PmenuThumb = { bg = "#89b4fa" },
	HLIndent1 = { fg = "#45475a" },
	HLIndent2 = { fg = "#45475a" },
	HLIndent3 = { fg = "#45475a" },
	HLIndent4 = { fg = "#45475a" },
	HLIndent5 = { fg = "#45475a" },
	HLChunk1 = { fg = "#fab387" },
	HLChunk2 = { fg = "#fab387" },
	HLChunk3 = { fg = "#fab387" },
	HLChunk4 = { fg = "#fab387" },
	HLChunk5 = { fg = "#fab387" },
	InclineNormal = { bg = "#181825" },
	InclineNormalNC = { bg = "#181825" },
	MintyFloatBorder = { fg = "#585b70", bg = "#1e1e2e" },
	MintyNormal = { bg = "#1e1e2e" },
	NoiceCmdlinePopup = { bg = "#1e1e2e", fg = "#cdd6f4" },
	NoiceCmdlinePopupBorder = { bg = "#1e1e2e", fg = "#585b70" },
	NoiceCmdlineIconCmdline = { bg = "#1e1e2e", fg = "#585b70" },
	NoiceCmdlineIcon = { bg = "#1e1e2e", fg = "#585b70" },
	NoiceCmdlinePopupTitle = { bg = "#1e1e2e", fg = "#89b4fa" },
	NoicePopup = { bg = "#1e1e2e", fg = "#cdd6f4" },
	NoicePopupBorder = { bg = "#1e1e2e", fg = "#585b70" },
	NoiceConfirm = { bg = "#1e1e2e", fg = "#cdd6f4" },
	NoiceConfirmBorder = { bg = "#1e1e2e", fg = "#585b70" },
	NoiceMini = { bg = "#1e1e2e", fg = "#cdd6f4" },
	NoiceFormatProgressDone = { bg = "#1e1e2e", fg = "#a6e3a1" },
	NoiceFormatProgressTodo = { bg = "#1e1e2e", fg = "#585b70" },
	NoiceFormatTitle = { bg = "#1e1e2e", fg = "#89b4fa" },
	NoiceFormatEvent = { bg = "#1e1e2e", fg = "#89dceb" },
	NoiceFormatKind = { bg = "#1e1e2e", fg = "#f9e2af" },
	NoiceFormatDate = { bg = "#1e1e2e", fg = "#cba6f7" },
	NoiceLspProgressTitle = { bg = "#1e1e2e", fg = "#89b4fa" },
	NoiceLspProgressClient = { bg = "#1e1e2e", fg = "#89dceb" },
	NoiceLspProgressSpinner = { bg = "#1e1e2e", fg = "#f9e2af" },
	NoiceCmdlinePrompt = { bg = "#1e1e2e", fg = "#89b4fa" },
	MsgArea = { bg = "#1e1e2e", fg = "#cdd6f4" },
	MsgSeparator = { bg = "#1e1e2e", fg = "#585b70" },
	NormalFloat = { bg = "#1e1e2e", fg = "#cdd6f4" },
	FloatBorder = { bg = "#1e1e2e", fg = "#585b70" },
	Pmenu = { bg = "#1e1e2e", fg = "#cdd6f4" },
	PmenuSel = { bg = "#313244", fg = "#cdd6f4" },
	PmenuBorder = { bg = "#1e1e2e", fg = "#585b70" },
	NeoTreeNormal = { bg = "#181825" },
	NeoTreeNormalNC = { bg = "#181825" },
	NeoTreeEndOfBuffer = { bg = "#181825", fg = "#181825" },
	ColorColumn = { bg = "#45475a" },
	VirtColumn = { fg = "#45475a" },
}

return highlights
