-- highlights-vscode-dark.lua
-- Custom highlight groups for VSCode Dark theme

local highlights = {
	NormalLineNr = { bg = "#1f1f1f" },
	LineNr = { bg = "#1f1f1f", fg = "#858585" },
	CursorLineNr = { bg = "#1f1f1f", fg = "#cccccc", bold = true },
	SignColumn = { bg = "#1f1f1f" },
	GitSignsAdd = { bg = "#1f1f1f", fg = "#587c0c" },
	GitSignsChange = { bg = "#1f1f1f", fg = "#0c7d9d" },
	GitSignsDelete = { bg = "#1f1f1f", fg = "#94151b" },
	DiagnosticSignError = { bg = "#1f1f1f", fg = "#f14c4c" },
	DiagnosticSignWarn = { bg = "#1f1f1f", fg = "#ff8c00" },
	DiagnosticSignInfo = { bg = "#1f1f1f", fg = "#3794ff" },
	DiagnosticSignHint = { bg = "#1f1f1f", fg = "#4ec9b0" },
	VertSplit = { fg = "#2d2d30", bg = "#1f1f1f" },
	WinSeparator = { fg = "#2d2d30", bg = "#1f1f1f" },
	BufferLineOffset = { bg = "#2d2d30", fg = "#2d2d30", bold = true },
	BufferLineOffsetSeparator = { bg = "#2d2d30", fg = "#2d2d30" },
	BufferLineFill = { bg = "#2d2d30" },
	TerminalNormal = { bg = "#1f1f1f" },
	TerminalBorder = { fg = "#1f1f1f", bg = "#1e1e1e" },
	Terminal = { bg = "#1f1f1f" },
	WhichKey = { fg = "#cccccc", bg = "#1f1f1f" },
	WhichKeyGroup = { fg = "#9cdcfe", bg = "#1f1f1f" },
	WhichKeyDesc = { fg = "#4fc1ff", bg = "#1f1f1f" },
	WhichKeyValue = { fg = "#4fc1ff", bg = "#1f1f1f" },
	WhichKeySeparator = { fg = "#858585", bg = "#1f1f1f" },
	WhichKeyFloat = { bg = "#1f1f1f" },
	WhichKeyBorder = { fg = "#858585", bg = "#1f1f1f" },
	WhichKeyTitle = { fg = "#858585", bg = "#1f1f1f" },
	WhichKeyNormal = { bg = "#1f1f1f" },
	CmpPmenu = { bg = "#1f1f1f", fg = "#cccccc" },
	CmpSel = { bg = "#094771", fg = "#cccccc" },
	CmpBorder = { fg = "#464647", bg = "#1f1f1f" },
	CmpDoc = { bg = "#1f1f1f", fg = "#cccccc" },
	CmpDocBorder = { fg = "#464647", bg = "#1f1f1f" },
	CmpItemKindText = { fg = "#cccccc" },
	CmpItemKindMethod = { fg = "#dcdcaa" },
	CmpItemKindFunction = { fg = "#dcdcaa" },
	CmpItemKindConstructor = { fg = "#dcdcaa" },
	CmpItemKindField = { fg = "#9cdcfe" },
	CmpItemKindVariable = { fg = "#9cdcfe" },
	CmpItemKindClass = { fg = "#4ec9b0" },
	CmpItemKindInterface = { fg = "#b5cea8" },
	CmpItemKindModule = { fg = "#4ec9b0" },
	CmpItemKindProperty = { fg = "#9cdcfe" },
	CmpItemKindUnit = { fg = "#b5cea8" },
	CmpItemKindValue = { fg = "#ce9178" },
	CmpItemKindEnum = { fg = "#4ec9b0" },
	CmpItemKindKeyword = { fg = "#569cd6" },
	CmpItemKindSnippet = { fg = "#d7ba7d" },
	CmpItemKindColor = { fg = "#ce9178" },
	CmpItemKindFile = { fg = "#cccccc" },
	CmpItemKindReference = { fg = "#9cdcfe" },
	CmpItemKindFolder = { fg = "#cccccc" },
	CmpItemKindEnumMember = { fg = "#4fc1ff" },
	CmpItemKindConstant = { fg = "#4fc1ff" },
	CmpItemKindStruct = { fg = "#4ec9b0" },
	CmpItemKindEvent = { fg = "#dcdcaa" },
	CmpItemKindOperator = { fg = "#cccccc" },
	CmpItemKindTypeParameter = { fg = "#4ec9b0" },
	CmpItemKindCodeium = { fg = "#4fc1ff" },
	CmpItemKindTextSel = { bg = "#cccccc", fg = "#1f1f1f", bold = true },
	CmpItemKindMethodSel = { bg = "#dcdcaa", fg = "#1f1f1f", bold = true },
	CmpItemKindFunctionSel = { bg = "#dcdcaa", fg = "#1f1f1f", bold = true },
	CmpItemKindConstructorSel = { bg = "#dcdcaa", fg = "#1f1f1f", bold = true },
	CmpItemKindFieldSel = { bg = "#9cdcfe", fg = "#1f1f1f", bold = true },
	CmpItemKindVariableSel = { bg = "#9cdcfe", fg = "#1f1f1f", bold = true },
	CmpItemKindClassSel = { bg = "#4ec9b0", fg = "#1f1f1f", bold = true },
	CmpItemKindInterfaceSel = { bg = "#b5cea8", fg = "#1f1f1f", bold = true },
	CmpItemKindModuleSel = { bg = "#4ec9b0", fg = "#1f1f1f", bold = true },
	CmpItemKindPropertySel = { bg = "#9cdcfe", fg = "#1f1f1f", bold = true },
	CmpItemKindUnitSel = { bg = "#b5cea8", fg = "#1f1f1f", bold = true },
	CmpItemKindValueSel = { bg = "#ce9178", fg = "#1f1f1f", bold = true },
	CmpItemKindEnumSel = { bg = "#4ec9b0", fg = "#1f1f1f", bold = true },
	CmpItemKindKeywordSel = { bg = "#569cd6", fg = "#1f1f1f", bold = true },
	CmpItemKindSnippetSel = { bg = "#d7ba7d", fg = "#1f1f1f", bold = true },
	CmpItemKindColorSel = { bg = "#ce9178", fg = "#1f1f1f", bold = true },
	CmpItemKindFileSel = { bg = "#cccccc", fg = "#1f1f1f", bold = true },
	CmpItemKindReferenceSel = { bg = "#9cdcfe", fg = "#1f1f1f", bold = true },
	CmpItemKindFolderSel = { bg = "#cccccc", fg = "#1f1f1f", bold = true },
	CmpItemKindEnumMemberSel = { bg = "#4fc1ff", fg = "#1f1f1f", bold = true },
	CmpItemKindConstantSel = { bg = "#4fc1ff", fg = "#1f1f1f", bold = true },
	CmpItemKindStructSel = { bg = "#4ec9b0", fg = "#1f1f1f", bold = true },
	CmpItemKindEventSel = { bg = "#dcdcaa", fg = "#1f1f1f", bold = true },
	CmpItemKindOperatorSel = { bg = "#cccccc", fg = "#1f1f1f", bold = true },
	CmpItemKindTypeParameterSel = { bg = "#4ec9b0", fg = "#1f1f1f", bold = true },
	CmpItemKindCodeiumSel = { bg = "#4fc1ff", fg = "#1f1f1f", bold = true },
	CmpScrollbar = { bg = "#2d2d30" },
	CmpScrollbarThumb = { bg = "#424242" },
	PmenuSbar = { bg = "#2d2d30" },
	PmenuThumb = { bg = "#424242" },
	HLIndent1 = { fg = "#404040" },
	HLChunk1 = { fg = "#569cd6" },
	InclineNormal = { bg = "#2d2d30" },
	InclineNormalNC = { bg = "#2d2d30" },
	MintyFloatBorder = { fg = "#464647", bg = "#1f1f1f" },
	MintyNormal = { bg = "#1f1f1f" },
	NoiceCmdlinePopup = { bg = "#1f1f1f", fg = "#cccccc" },
	NoiceCmdlinePopupBorder = { bg = "#1f1f1f", fg = "#464647" },
	NoiceCmdlineIconCmdline = { bg = "#1f1f1f", fg = "#464647" },
	NoiceCmdlineIcon = { bg = "#1f1f1f", fg = "#464647" },
	NoiceCmdlinePopupTitle = { bg = "#1f1f1f", fg = "#4fc1ff" },
	NoicePopup = { bg = "#1f1f1f", fg = "#cccccc" },
	NoicePopupBorder = { bg = "#1f1f1f", fg = "#464647" },
	NoiceConfirm = { bg = "#1f1f1f", fg = "#cccccc" },
	NoiceConfirmBorder = { bg = "#1f1f1f", fg = "#464647" },
	NoiceMini = { bg = "#1f1f1f", fg = "#cccccc" },
	NoiceFormatProgressDone = { bg = "#1f1f1f", fg = "#587c0c" },
	NoiceFormatProgressTodo = { bg = "#1f1f1f", fg = "#858585" },
	NoiceFormatTitle = { bg = "#1f1f1f", fg = "#4fc1ff" },
	NoiceFormatEvent = { bg = "#1f1f1f", fg = "#4ec9b0" },
	NoiceFormatKind = { bg = "#1f1f1f", fg = "#dcdcaa" },
	NoiceFormatDate = { bg = "#1f1f1f", fg = "#d7ba7d" },
	NoiceLspProgressTitle = { bg = "#1f1f1f", fg = "#4fc1ff" },
	NoiceLspProgressClient = { bg = "#1f1f1f", fg = "#4ec9b0" },
	NoiceLspProgressSpinner = { bg = "#1f1f1f", fg = "#dcdcaa" },
	NoiceCmdlinePrompt = { bg = "#1f1f1f", fg = "#4fc1ff" },
	MsgArea = { bg = "#1f1f1f", fg = "#cccccc" },
	MsgSeparator = { bg = "#1f1f1f", fg = "#464647" },
	NormalFloat = { bg = "#1f1f1f", fg = "#cccccc" },
	FloatBorder = { bg = "#1f1f1f", fg = "#464647" },
	Pmenu = { bg = "#252526", fg = "#cccccc" },
	PmenuSel = { bg = "#094771", fg = "#cccccc" },
	PmenuBorder = { bg = "#252526", fg = "#464647" },
	NeoTreeNormal = { bg = "#2D2D30" },
	NeoTreeNormalNC = { bg = "#2D2D30" },
	NeoTreeEndOfBuffer = { bg = "#2D2D30", fg = "#2D2D30" },
	NeoTreeWinSeparator = { fg = "#2D2D30", bg = "#2D2D30" },
	NeoTreeGitAdded = { bg = "#2D2D30", fg = "#587C0C" },
	NeoTreeGitConflict = { bg = "#2D2D30", fg = "#f14c4c" },
	NeoTreeGitDeleted = { bg = "#2D2D30", fg = "#94151b" },
	NeoTreeGitIgnored = { bg = "#2D2D30", fg = "#6a6a6a" },
	NeoTreeGitModified = { bg = "#2D2D30", fg = "#0c7d9d" },
	NeoTreeGitUnstaged = { bg = "#2D2D30", fg = "#ff8c00" },
	NeoTreeGitUntracked = { bg = "#2D2D30", fg = "#4ec9b0" },
	NeoTreeGitStaged = { bg = "#2D2D30", fg = "#587C0C" },
	NeoTreeCursorLine = { bg = "#1f1f1f" },
	NeoTreeExpander = { bg = "#2D2D30" },
	EndOfBuffer = { fg = "#1f1f1f" },
	ColorColumn = { bg = "#2d2d30" },
	VirtColumn = { fg = "#2d2d30" },
}

return highlights
